name: proyectos_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.17.5
  url_launcher: ^6.3.0
  mysql1: ^0.20.0
  crypto: ^3.0.3
  firebase_storage: ^11.7.7
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
